### ISSUE TITLE
Lexer doesn't handle all numbers

### ISSUE THREAD

**Issue by paf31** [purescript/purescript-in-purescript#11]

**Comment by garyb** [comment]
Lexer works for nats, floats, and hex now, but still need to do exponential notation. Are there any other formats we want to support?

I take it we're not lexing signed numbers, as that will interfere with the `negate` stuff? In which case, we probably don't need the `Integer` dctor (and we'll need `Exponential`). Do we actually need the separation between the different number formats anyway? I guess `Natural` is useful for fixity declarations, etc, but we could just use `Number` to cover everything else.

**Comment by paf31** [comment]
Looks fantastic. Right now, negative literals are handled by the unary `-` operator and a desugaring rule, so I think this gives us everything we need except for exponential notation.
