### ISSUE TITLE
Implement the optimizer

### ISSUE THREAD

**Issue by paf31** [purescript/purescript-in-purescript#19]
- [x] src/Language/PureScript/Optimizer/Blocks.hs
- [x] src/Language/PureScript/Optimizer/Common.hs
- [x] src/Language/PureScript/Optimizer/Inliner.hs
- [x] src/Language/PureScript/Optimizer/MagicDo.hs
- [x] src/Language/PureScript/Optimizer/TCO.hs
- [x] src/Language/PureScript/Optimizer/Unused.hs
- [x] src/Language/PureScript/Optimizer.hs

**Comment by garyb** [comment]
All these are done now, but the unchecked items need some stuff uncommenting (and then perhaps fixing) when purescript/purescript#427 is fixed.

**Comment by garyb** [comment]
Also I must admit I've not checked if it actually works, but I have to leave this for now. I'll be back later to test things and fix the referenced issue.

**Comment by paf31** [comment]
I've uncommented the commented code, and things compile, but there are issues with TCO. There are `JSFunction`s whose arguments lists are `undefined`.

**Comment by paf31** [comment]
This is great by the way :+1:
