### ISSUE TITLE
Support Haskell-style multiline strings in the lexer

### ISSUE THREAD

**Issue by paf31** [purescript/purescript-in-purescript#25]

**Comment by garyb** [comment]
I've done something for this, but only for `"` string literals, not `"""` - are they going to both exist still, and if so what are the rules for each? Do we want to do something like C#'s `@"` literals with `"""`? It'd certainly be nicer for writing regex strings like the ridiculous one I made for this fix! (`"\\\\\\s*\\n\\s*\\\\"`)

Also, as I'm sure you know, at the moment any string can be multiline as we just keep reading ahead until the string is closed or EOF is reached, do we want that to be the case, or should we only allow multiline strings with `"""` and Haskell-style `\` usage within `"` strings?

**Comment by paf31** [comment]
So I think I would like to support both `\ ... \` style strings as well as one of the `"""` and `@"` styles.

I don't think a regular string with newlines will currently lex correctly, but I might be wrong.

**Comment by jdegoes** [comment]
I suggest triple quotes """, more verbose but more common.

**Comment by garyb** [comment]
Agreed, and that's what we have at the moment, I was using the other thing as an example.

**Comment by paf31** [comment]
So this one can be closed, right?

**Comment by garyb** [comment]
Yep, but we probably need a new issue about how `"""` strings should behave - if they're "verbatim" strings, or what.
