### ISSUE TITLE
Use purescript-node-fs

### ISSUE THREAD

**Issue by paf31** [purescript/purescript-in-purescript#27]

**Comment by garyb** [comment]
It's not quite ready yet, I need to figure out how to make exceptions catchable for the functions in `Sync`. I tried something I thought would work, but it doesn't quite. I'll hopefully spend some time on it later tonight.

**Comment by paf31** [comment]
So, I made a `Control.Monad.Eff.FS` module for now. I'm using all synchronous things and handling exceptions in the FFI, but we can almost certainly improve it.

Also, `exceptions` is unsafe, and needs to be updated, so if we plan to use it, we should probably fix that first.

We don't have to do this immediately or anything. I'm just making a note for later.
