### ISSUE TITLE
Avoid hacky usage of `argv` in `Language.PureScript.Prelude`

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-in-purescript#30]
I started work on this, but it means updating `Compiler`, `Interpreter`, etc. as well due to the introduction of `Eff`.

``` haskell
module Language.PureScript.Prelude where

import Control.Monad.Eff
import Data.Array (map)
import Node.Args (EArgs(), argv)
import Node.Path
import Prelude.Unsafe

preludeFiles :: forall eff. Eff (args :: EArgs | eff) [String]
preludeFiles = do
  args <- argv
  let preludeBaseDir = join (dirname $ args `unsafeIndex` 1) "../prelude/"
  return $ map (\x -> preludeBaseDir ++ x)
               [ "Prelude.purs"
               , "Prelude/Unsafe.purs"
               , "Control/Monad/Eff.purs"
               , "Control/Monad/Eff/Unsafe.purs"
               , "Control/Monad/ST.purs"
               , "Data/Eq.purs"
               , "Data/Function.purs"
               , "Debug/Trace.purs"
               ]
```

**Comment by paf31** [comment]
I'm generally of the opinion that things like this are "pure enough".

**Comment by garyb** [comment]
Oh ok, cool. I just had second thoughts after committing last night, given that we have an existing effect for it in `Node.Args`.

**Comment by paf31** [comment]
Well, I don't mind. I'm just saying that something like "the result depends on the location of the executable" is slightly less bad in some sense than "the result depends on the time" or "the result depends on some global var".
