### ISSUE TITLE
New website

### ISSUE THREAD

**Issue by paf31** [purescript/purescript-in-purescript#32]

**Comment by garyb** [comment]
I think one thing we need to work on for sure is exposing the packages (both in core and contrib) a bit better, I get the impression people still don't know about them and end up redefining stuff that has already been done.

**Comment by joneshf** [comment]
This is very true. The other thing is, knowing what is in different packages. It'd be great to have a hoogle/hayoo thing going on here

**Comment by jdegoes** [comment]
+1

**Comment by garyb** [comment]
Closing this in favour of purescript/purescript#467

**Comment by paf31** [comment]
Oops, forgot about this one :)
