### ISSUE TITLE
Make failed 

### ISSUE THREAD

**Issue by legokichi** [purescript/purescript-in-purescript#38]
2f8352d000cbf2ba291aceb036beb0fd5d3a294e

I want to use purescript-in-purescript, but it cannot make.

here is error log.

```
$ psc --version
0.5.1

$ grunt
Running "pscMake:0" (pscMake) task
>> Make failed:
>> "src/Language/PureScript/Parser/Lexer.purs" (line 5, column 20):
>> unexpected 'h'
>> expecting no indentation or end of input
Warning:  Use --force to continue.

Aborted due to warnings.
```

What can I do?

**Comment by joneshf** [comment]
The `import <module> hiding <stuff>` clause was made available inthe `0.5.4.1` release. You'll want to update to at least this version. In fact, given that some standard things depend on the latest compiler version, you'll probably want to update to the latest. That said, there's a good chance ps-in-ps isn't going to be able to compile most of the newer versions of things.

**Comment by garyb** [comment]
I fixed `purescript-in-purescript` last night so it does now compile with `psc` from master.

**Comment by garyb** [comment]
@joneshf is right in that `purescript-in-purescript` won't be able to compile a lot of things at the moment though. Even when it was up to date it still needed work to be able to compile anything other than itself.

**Comment by legokichi** [comment]
Yes, I reinstall  `0.5.6.3`, it works. 
Thank you.
