### ISSUE TITLE
Remaining Modules

### ISSUE THREAD

**Issue by paf31** [purescript/purescript-in-purescript#5]
@garyb 

Let's check these off as we finish them.

We can use the comments to assign these to ourselves so we don't duplicate work.
- Code Generator (Simple but large modules)
  - [x] src/Language/PureScript/CodeGen/Common.hs
  - [x] src/Language/PureScript/CodeGen/Externs.hs
  - [x] src/Language/PureScript/CodeGen/JS/AST.hs
  - [x] src/Language/PureScript/CodeGen/JS.hs
- Optimizer (medium, low priority)
  - [ ] src/Language/PureScript/Optimizer/Blocks.hs
  - [ ] src/Language/PureScript/Optimizer/Common.hs
  - [ ] src/Language/PureScript/Optimizer/Inliner.hs
  - [ ] src/Language/PureScript/Optimizer/MagicDo.hs
  - [ ] src/Language/PureScript/Optimizer/TCO.hs
  - [ ] src/Language/PureScript/Optimizer/Unused.hs
- Data Types
  - [x] src/Language/PureScript/Declarations.hs
  - [x] src/Language/PureScript/Environment.hs
  - [x] src/Language/PureScript/Errors.hs
  - [x] src/Language/PureScript/Kinds.hs
  - [x] src/Language/PureScript/Options.hs
  - [x] src/Language/PureScript/Names.hs
  - [x] src/Language/PureScript/TypeClassDictionaries.hs
  - [x] src/Language/PureScript/Types.hs
- Parser
  - [x] src/Language/PureScript/Parser/Common.hs
  - [x] src/Language/PureScript/Parser/Declarations.hs
  - [x] src/Language/PureScript/Parser/Kinds.hs
  - [x] src/Language/PureScript/Parser/Types.hs
- Pretty Printer (Difficult)
  - [x] src/Language/PureScript/Pretty/Common.hs
  - [x] src/Language/PureScript/Pretty/JS.hs
  - [x] src/Language/PureScript/Pretty/Kinds.hs
  - [x] src/Language/PureScript/Pretty/Types.hs
  - [x] src/Language/PureScript/Pretty/Values.hs
- Desugaring Steps
  - [x] src/Language/PureScript/Sugar/BindingGroups.hs
  - [x] src/Language/PureScript/Sugar/CaseDeclarations.hs
  - [x] src/Language/PureScript/Sugar/DoNotation.hs
  - [x] src/Language/PureScript/Sugar/Names.hs
  - [x] src/Language/PureScript/Sugar/Operators.hs
  - [x] src/Language/PureScript/Sugar/TypeClasses.hs
  - [x] src/Language/PureScript/Sugar/TypeDeclarations.hs
  - [x] src/Language/PureScript/Sugar.hs
- Type Checker (Difficult)
  - [x] src/Language/PureScript/TypeChecker/Kinds.hs
  - [x] src/Language/PureScript/TypeChecker/Monad.hs
  - [x] src/Language/PureScript/TypeChecker/Synonyms.hs
  - [x] src/Language/PureScript/TypeChecker/Types.hs
  - [x] src/Language/PureScript/TypeChecker.hs
- Other
  - [ ] src/Language/PureScript/DeadCodeElimination.hs
  - [x] src/Language/PureScript/Constants.hs
  - [x] src/Language/PureScript/ModuleDependencies.hs
  - [x] src/Language/PureScript/Supply.hs
  - [x] src/Language/PureScript/Traversals.hs
  - [x] src/Language/PureScript.hs

**Comment by paf31** [comment]
I'll take `src/Language/PureScript/Sugar/BindingGroups.hs`

**Comment by garyb** [comment]
Carrying on with `src/Language/PureScript/CodeGen/JS.hs` now I'm done with `Supply`

**Comment by paf31** [comment]
The desugaring modules are almost done. You can step through from lexing to parsing to desugaring to codegen now in the REPL, for a simple module, and see some actual JS AST output. :+1:

**Comment by puffnfresh** [comment]
:fireworks: 

And almost 70% of modules are marked as done! Woo!

**Comment by garyb** [comment]
@paf31 Made some progress with `src/Language/PureScript/TypeChecker/Types`, but there's still plenty to do. I'm not going to be around until later tonight again, so if you want to carry on with it go ahead. 

There's some stuff using comprehensions that look pretty crazy, if you get a chance to have a look at those it'd be very helpful, as at least you know what they're supposed to be doing!

**Comment by paf31** [comment]
@garyb I'll probably try to finish off `Sugar` today, but I'll be off and on all day. The type checker is looking great though :)

**Comment by paf31** [comment]
I'm going to close this and reopen separate tickets for the remaining items.
